/* ============================================================
   LeaseLoops — Data (mock listings + roommate profiles)
   TCU-focused housing marketplace
   ============================================================ */

const CAMPUSES = [
  /* TCU is first intentionally — array order = default campus priority in UI.
     getCurrentCampus() defaults to 'TCU'; the switcher modal also uses this order. */
  { id: 'tcu',         name: 'TCU',                  emoji: '🐸', city: 'Fort Worth, TX' },
  { id: 'ut-austin',   name: 'UT Austin',            emoji: '🤘', city: 'Austin, TX' },
  { id: 'baylor',      name: 'Baylor',               emoji: '🐻', city: 'Waco, TX' },
  { id: 'tamu',        name: 'Texas A&M',            emoji: '🐾', city: 'College Station, TX' },
  { id: 'smu',         name: 'SMU',                  emoji: '🏛',  city: 'Dallas, TX' },
  { id: 'unt',         name: 'UNT',                  emoji: '🦅', city: 'Denton, TX' },
  { id: 'ttu',         name: 'Texas Tech',           emoji: '🔴', city: 'Lubbock, TX' },
  { id: 'uh',          name: 'University of Houston',emoji: '🏙',  city: 'Houston, TX' },
];

const PROPERTY_TYPES = ['Apartment','House','Studio','Room','Condo','Duplex','Townhome','Sublease'];

const listings = [
  // ── TCU Featured Listings (60%+ of mock data) ──────────────
  {
    id: 101, title: 'Modern 2BR near TCU — Campus Commons', price: 875, priceUnit: 'month',
    location: 'Campus Commons, 0.2 mi from TCU', city: 'Fort Worth, TX', campus: 'TCU',
    bedrooms: 2, bathrooms: 2, sqft: 920, type: 'Apartment', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Pets OK (deposit required)', parking: 'Covered included',
    utilities: ['Water', 'Trash', 'Internet'],
    description: 'Fresh 2-bed 2-bath apartment at Campus Commons — the spot for TCU students. Updated kitchen, in-unit W/D, pool & gym. Walk to class in minutes! Horned Frog approved 🐸',
    amenities: ['In-unit W/D','Pool','Gym','Covered parking','Internet included','Dishwasher','Central A/C'],
    landlord: 'TCU Campus Housing', landlordEmail: 'leasing@tcucampushousing.com', landlordPhone: '(817) 555-0100',
    landlordType: 'Realtor', agency: 'TCU Campus Rentals',
    featured: true, saved: false, icon: '🏢', rating: 4.9, reviews: 28, views: 612, inquiries: 14,
    status: 'available', postedBy: null,
  },
  {
    id: 102, title: 'Cozy 1BR Studio — University Drive', price: 695, priceUnit: 'month',
    location: 'University Drive, steps from TCU', city: 'Fort Worth, TX', campus: 'TCU',
    bedrooms: 0, bathrooms: 1, sqft: 490, type: 'Studio', available: 'July 2025',
    leaseLength: '12 months', petPolicy: 'No pets', parking: 'Street parking',
    utilities: ['All included'],
    description: 'Cute studio right on University Drive. All utilities included! Perfect for the TCU student who wants to keep it simple and affordable. Super walkable to campus and dining.',
    amenities: ['All utilities included','Laundry on-site','Bike storage','Walk to campus','Near restaurants'],
    landlord: 'Maria Chen', landlordEmail: 'mchen@fwhousing.com', landlordPhone: '(817) 555-0237',
    landlordType: 'Private', agency: null,
    featured: true, saved: false, icon: '🏠', rating: 4.6, reviews: 10, views: 290, inquiries: 7,
    status: 'available', postedBy: null,
  },
  {
    id: 103, title: 'Spacious 4BR House — Westberry Place', price: 650, priceUnit: 'person/month',
    location: 'Westberry Place, 0.5 mi from TCU', city: 'Fort Worth, TX', campus: 'TCU',
    bedrooms: 4, bathrooms: 2, sqft: 1850, type: 'House', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Dogs & Cats OK', parking: '2 spots included',
    utilities: ['Water', 'Trash'],
    description: 'Big 4BR house perfect for a group of TCU friends! Huge backyard for tailgates, 2 full baths, and a game room. Short bike to campus. Split rent between 4 people — super affordable!',
    amenities: ['Backyard','Game room','2 full baths','Central A/C','Dishwasher','Pet friendly','2 parking spots'],
    landlord: 'Tom Williams', landlordEmail: 'twilliams@fwrentals.com', landlordPhone: '(817) 555-0099',
    landlordType: 'Private', agency: null,
    featured: true, saved: false, icon: '🏡', rating: 4.8, reviews: 18, views: 540, inquiries: 12,
    status: 'available', postedBy: null,
  },
  {
    id: 104, title: 'Private Room in 3BR Apt — TCU Area', price: 700, priceUnit: 'month',
    location: 'Near TCU Main Campus', city: 'Fort Worth, TX', campus: 'TCU',
    bedrooms: 1, bathrooms: 1, sqft: 200, type: 'Room', available: 'June 2025',
    leaseLength: '9 months', petPolicy: 'No pets', parking: 'Building lot',
    utilities: ['All included'],
    description: 'Private furnished bedroom in a 3-bedroom apartment shared with two other TCU students. Large common area, great roommates, quiet environment. Bills split equally. 🐸',
    amenities: ['Furnished bedroom','Shared kitchen','WiFi included','Pool access','Gym in building'],
    landlord: 'Sarah Park', landlordEmail: 'sarah.park@tcuhousing.com', landlordPhone: '(817) 555-0340',
    landlordType: 'Private', agency: null,
    featured: true, saved: false, icon: '🛏', rating: 4.6, reviews: 5, views: 112, inquiries: 4,
    status: 'available', postedBy: null,
  },
  {
    id: 105, title: 'TCU Sublease — 2BR Aug–Dec', price: 800, priceUnit: 'month',
    location: '0.3 mi from TCU, near Stadium', city: 'Fort Worth, TX', campus: 'TCU',
    bedrooms: 2, bathrooms: 1, sqft: 880, type: 'Sublease', available: 'August 2025',
    leaseLength: 'Aug–Dec (short-term)', petPolicy: 'No pets', parking: 'Gated lot',
    utilities: ['Water', 'Internet'],
    description: 'Need a sublease for the fall semester? This 2BR right near TCU stadium is perfect! Fully furnished, gated parking, steps from campus. Roommate is chill TCU senior.',
    amenities: ['Furnished','Gated parking','Near stadium','WiFi included','Short-term OK','Pool'],
    landlord: 'Jake Morrison', landlordEmail: 'jake.sublease@tcu.edu', landlordPhone: '(817) 555-0488',
    landlordType: 'Private', agency: null,
    featured: true, saved: false, icon: '🔑', rating: 4.5, reviews: 4, views: 143, inquiries: 6,
    status: 'available', postedBy: null,
  },
  {
    id: 106, title: 'New 3BR Townhome — TCU Village', price: 950, priceUnit: 'month',
    location: 'TCU Village, Fort Worth', city: 'Fort Worth, TX', campus: 'TCU',
    bedrooms: 3, bathrooms: 2, sqft: 1400, type: 'Townhome', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Small pets OK', parking: 'Attached garage',
    utilities: ['Water', 'Trash'],
    description: 'Brand-new townhome in the TCU Village development. Each bedroom has its own lock, attached garage, and a rooftop terrace. TCU gameday vibes year-round. 🏆',
    amenities: ['Rooftop terrace','Attached garage','New appliances','Private bedrooms','2 full baths','Central A/C'],
    landlord: 'Fort Worth Properties', landlordEmail: 'leasing@fwproperties.com', landlordPhone: '(817) 555-0520',
    landlordType: 'Realtor', agency: 'Fort Worth Properties',
    featured: true, saved: false, icon: '🏘', rating: 4.9, reviews: 8, views: 385, inquiries: 10,
    status: 'available', postedBy: null,
  },
  {
    id: 107, title: 'Budget 2BR Near TCU Bus Stop', price: 720, priceUnit: 'month',
    location: '0.8 mi from TCU, bus route', city: 'Fort Worth, TX', campus: 'TCU',
    bedrooms: 2, bathrooms: 1, sqft: 810, type: 'Apartment', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Cats OK', parking: 'Street parking',
    utilities: ['Water'],
    description: 'Affordable 2BR on the TCU bus route — save money without sacrificing convenience. Updated kitchen, nice natural light, quiet building. Great for budget-conscious Frogs!',
    amenities: ['Bus route','Updated kitchen','Natural light','Laundry on-site','Cat-friendly','Quiet building'],
    landlord: 'Anna Rogers', landlordEmail: 'anna.r@gmail.com', landlordPhone: '(817) 555-0613',
    landlordType: 'Private', agency: null,
    featured: false, saved: false, icon: '🏠', rating: 4.3, reviews: 7, views: 164, inquiries: 3,
    status: 'available', postedBy: null,
  },
  // ── Other Campus Listings ───────────────────────────────────
  {
    id: 1, title: 'Modern 2BR Near Campus', price: 850, priceUnit: 'month',
    location: '0.3 miles from UT Austin', city: 'Austin, TX', campus: 'UT Austin',
    bedrooms: 2, bathrooms: 1, sqft: 875, type: 'Apartment', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Pets OK (deposit required)', parking: 'Included',
    utilities: ['Water', 'Trash'],
    description: 'Bright, fully furnished 2-bedroom apartment just steps from UT campus. Updated kitchen, hardwood floors, in-unit washer/dryer. Perfect for two roommates.',
    amenities: ['In-unit W/D','Dishwasher','Hardwood floors','Central A/C','Parking included','Furnished option'],
    landlord: 'Alex Johnson', landlordEmail: 'alex.johnson@realty.com', landlordPhone: '(512) 555-0182',
    landlordType: 'Realtor', agency: 'Capitol City Realty',
    featured: true, saved: false, icon: '🏢', rating: 4.8, reviews: 14, views: 342, inquiries: 8,
    status: 'available', postedBy: null,
  },
  {
    id: 2, title: 'Cozy Studio — Walk to Baylor', price: 620, priceUnit: 'month',
    location: '0.2 miles from Baylor', city: 'Waco, TX', campus: 'Baylor',
    bedrooms: 0, bathrooms: 1, sqft: 480, type: 'Studio', available: 'July 2025',
    leaseLength: '12 months', petPolicy: 'No pets', parking: 'Street parking',
    utilities: ['Water', 'Electricity', 'Internet'],
    description: 'Charming studio apartment within walking distance of Baylor University. All utilities included in rent. Quiet building, great for studying.',
    amenities: ['All utilities included','Street parking','Quiet building','Laundry on-site','Near bus route'],
    landlord: 'Maria Chen', landlordEmail: 'mchen@housing.com', landlordPhone: '(254) 555-0237',
    landlordType: 'Private', agency: null,
    featured: false, saved: false, icon: '🏠', rating: 4.5, reviews: 8, views: 210, inquiries: 4,
    status: 'available', postedBy: null,
  },
  {
    id: 3, title: 'Spacious 4BR House — A&M', price: 600, priceUnit: 'person/month',
    location: '0.5 miles from Texas A&M', city: 'College Station, TX', campus: 'Texas A&M',
    bedrooms: 4, bathrooms: 2, sqft: 1800, type: 'House', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Dogs & Cats OK', parking: '2 spots included',
    utilities: ['Water', 'Trash'],
    description: 'Large 4-bedroom house perfect for a group of friends. Big backyard, two full baths, garage with extra storage. Short drive or bike ride to Texas A&M.',
    amenities: ['Backyard','Garage','2 full baths','Central A/C & Heat','Dishwasher','2 parking spots'],
    landlord: 'Tom Williams', landlordEmail: 'twilliams@tamu-rentals.com', landlordPhone: '(979) 555-0099',
    landlordType: 'Private', agency: null,
    featured: false, saved: false, icon: '🏡', rating: 4.7, reviews: 22, views: 518, inquiries: 11,
    status: 'available', postedBy: null,
  },
  {
    id: 5, title: 'Luxury 1BR Condo — SMU', price: 1400, priceUnit: 'month',
    location: '0.1 miles from SMU', city: 'Dallas, TX', campus: 'SMU',
    bedrooms: 1, bathrooms: 1, sqft: 720, type: 'Condo', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Small pets OK', parking: 'Covered included',
    utilities: ['Water', 'Trash', 'Internet'],
    description: 'Upscale 1-bedroom condo steps from SMU. Granite countertops, stainless appliances, balcony with city views. Concierge, rooftop pool, and fitness center included.',
    amenities: ['Rooftop pool','Fitness center','Concierge','Balcony','Covered parking','Stainless appliances'],
    landlord: 'James Realty Group', landlordEmail: 'leasing@jamesrealty.com', landlordPhone: '(214) 555-0078',
    landlordType: 'Realtor', agency: 'James Realty Group',
    featured: false, saved: false, icon: '🏙', rating: 4.9, reviews: 31, views: 872, inquiries: 19,
    status: 'available', postedBy: null,
  },
  {
    id: 6, title: 'Affordable 2BR Duplex — UNT', price: 750, priceUnit: 'month',
    location: '0.6 miles from UNT', city: 'Denton, TX', campus: 'UNT',
    bedrooms: 2, bathrooms: 1, sqft: 950, type: 'Duplex', available: 'September 2025',
    leaseLength: '12 months', petPolicy: 'Cats allowed', parking: 'Street parking',
    utilities: ['Water'],
    description: 'Charming duplex with private entrance and fenced yard. Two spacious bedrooms, updated kitchen, and a covered porch. Quiet street, great for studying.',
    amenities: ['Private entrance','Fenced yard','Covered porch','Cats allowed','Storage shed'],
    landlord: 'Linda Carter', landlordEmail: 'linda@unt-rentals.net', landlordPhone: '(940) 555-0214',
    landlordType: 'Private', agency: null,
    featured: false, saved: false, icon: '🏘', rating: 4.3, reviews: 9, views: 154, inquiries: 2,
    status: 'available', postedBy: null,
  },
  {
    id: 7, title: '3BR Townhome — Texas Tech', price: 800, priceUnit: 'month',
    location: '0.8 miles from Texas Tech', city: 'Lubbock, TX', campus: 'Texas Tech',
    bedrooms: 3, bathrooms: 2, sqft: 1350, type: 'Townhome', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Dogs OK', parking: 'Attached garage',
    utilities: ['Water', 'Trash'],
    description: 'Well-maintained 3-bedroom townhome with attached garage. Two-story layout, large master suite, community pool. Close to Tech campus and restaurants.',
    amenities: ['Attached garage','Community pool','Master suite','2 full baths','Dishwasher'],
    landlord: 'West Texas Properties', landlordEmail: 'info@wtproperties.com', landlordPhone: '(806) 555-0155',
    landlordType: 'Realtor', agency: 'West Texas Properties',
    featured: false, saved: false, icon: '🏠', rating: 4.4, reviews: 17, views: 203, inquiries: 6,
    status: 'available', postedBy: null,
  },
  {
    id: 8, title: 'Sublease — 1BR near UH', price: 900, priceUnit: 'month',
    location: '0.3 miles from U of Houston', city: 'Houston, TX', campus: 'University of Houston',
    bedrooms: 1, bathrooms: 1, sqft: 650, type: 'Sublease', available: 'May 2025',
    leaseLength: 'May–August (short-term)', petPolicy: 'No pets', parking: 'Gated lot',
    utilities: ['All included'],
    description: 'Short-term sublease available May through August. Fully furnished 1BR in a gated community. All utilities included. Great for summer semester students.',
    amenities: ['Fully furnished','All utilities included','Gated community','Pool & gym','Short-term OK'],
    landlord: 'Priya Nair', landlordEmail: 'priya.sublease@gmail.com', landlordPhone: '(713) 555-0387',
    landlordType: 'Private', agency: null,
    featured: false, saved: false, icon: '🔑', rating: 4.2, reviews: 3, views: 96, inquiries: 2,
    status: 'available', postedBy: null,
  },
  {
    id: 9, title: 'Budget Studio — UT Austin', price: 550, priceUnit: 'month',
    location: '1.1 miles from UT Austin', city: 'Austin, TX', campus: 'UT Austin',
    bedrooms: 0, bathrooms: 1, sqft: 420, type: 'Studio', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'No pets', parking: 'Street parking',
    utilities: ['Water'],
    description: 'Affordable studio for students on a budget. Clean, safe building with laundry and bike storage. Bus stop outside — easy commute to campus.',
    amenities: ['Laundry on-site','Bike storage','Bus stop outside','Water included','Secure entry'],
    landlord: 'Austin Campus Housing', landlordEmail: 'contact@austincampushousing.com', landlordPhone: '(512) 555-0044',
    landlordType: 'Realtor', agency: 'Austin Campus Housing',
    featured: false, saved: false, icon: '🏠', rating: 4.0, reviews: 6, views: 178, inquiries: 3,
    status: 'available', postedBy: null,
  },
  {
    id: 10, title: 'Roomy 2BR Apt with Pool — SMU', price: 1100, priceUnit: 'month',
    location: '0.7 miles from SMU', city: 'Dallas, TX', campus: 'SMU',
    bedrooms: 2, bathrooms: 2, sqft: 1050, type: 'Apartment', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Small pets OK', parking: 'Covered included',
    utilities: ['Water', 'Trash', 'Internet'],
    description: 'Spacious 2-bed 2-bath with resort-style pool and clubhouse. Each roommate gets a private bath. Walking distance to SMU and Greenville Ave restaurants.',
    amenities: ['Resort-style pool','Clubhouse','2 private baths','Valet trash','Package lockers','Covered parking'],
    landlord: 'Uptown Living LLC', landlordEmail: 'leasing@uptownliving.com', landlordPhone: '(214) 555-0201',
    landlordType: 'Realtor', agency: 'Uptown Living LLC',
    featured: false, saved: false, icon: '🏊', rating: 4.7, reviews: 19, views: 432, inquiries: 9,
    status: 'available', postedBy: null,
  },
];

/* ── Sample Roommate Profiles ─────────────────────────────── */
const roommateProfiles = [
  // TCU-first profiles
  {
    id: 'r5', name: 'Tyler Brooks', age: 23, gender: 'Male',
    campus: 'TCU', major: 'Education', year: 'Senior',
    budget: { min: 600, max: 900 }, moveIn: 'July 2025', leaseDuration: '9 months',
    sleepSchedule: 'Early bird 🐦', cleanliness: 4, noise: 'Quiet', guests: 'Rarely',
    smoking: false, pets: true, bio: 'Future teacher and dog dad 🐶. My golden retriever Biscuit is the best co-pilot. Tidy, low-key, love a clean space. Go Frogs! 🐸',
    interests: ['Dogs', 'Running', 'Teaching', 'Basketball', 'Podcasts'], initials: 'TB',
  },
  {
    id: 'r9', name: 'Chloe Martinez', age: 20, gender: 'Female',
    campus: 'TCU', major: 'Business', year: 'Sophomore',
    budget: { min: 650, max: 950 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Night owl 🦉', cleanliness: 4, noise: 'Moderate', guests: 'Sometimes',
    smoking: false, pets: false, bio: 'TCU business student — future CEO, current coffee addict ☕. Love brunch, purple & white gameday, and keeping common areas clean. Looking for a fun but responsible roomie!',
    interests: ['Business', 'Gameday', 'Coffee', 'Fashion', 'Networking'], initials: 'CM',
  },
  {
    id: 'r10', name: 'Marcus Johnson', age: 22, gender: 'Male',
    campus: 'TCU', major: 'Kinesiology', year: 'Junior',
    budget: { min: 550, max: 850 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Early bird 🐦', cleanliness: 4, noise: 'Quiet', guests: 'Sometimes',
    smoking: false, pets: false, bio: 'Kinesiology major and avid Horned Frog fan 🐸. I\'m up early for practice and in bed by 11. Super tidy, love to cook, and always down to watch TCU football!',
    interests: ['Football', 'Gym', 'Cooking', 'Kinesiology', 'TCU sports'], initials: 'MJ',
  },
  {
    id: 'r11', name: 'Lily Nguyen', age: 19, gender: 'Female',
    campus: 'TCU', major: 'Design', year: 'Freshman',
    budget: { min: 600, max: 900 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Night owl 🦉', cleanliness: 5, noise: 'Quiet', guests: 'Rarely',
    smoking: false, pets: true, bio: 'Design freshman with an aesthetic apartment board and a tiny cat named Pixel 🐱. I\'m quiet, keep things super tidy, and love cozy movie nights. Let\'s make our apartment cute!',
    interests: ['Design', 'Art', 'Movies', 'Cats', 'Aesthetic living'], initials: 'LN',
  },
  // Other campus profiles
  {
    id: 'r1', name: 'Jordan Lee', age: 21, gender: 'Non-binary',
    campus: 'UT Austin', major: 'Computer Science', year: 'Junior',
    budget: { min: 600, max: 900 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Night owl 🦉', cleanliness: 4, noise: 'Moderate', guests: 'Sometimes',
    smoking: false, pets: false, bio: 'CS major who loves hackathons, hiking around Austin, and cooking for friends. Looking for a chill roommate who won\'t mind me occasionally coding late.',
    interests: ['Coding', 'Hiking', 'Cooking', 'Gaming', 'Music'], initials: 'JL',
  },
  {
    id: 'r2', name: 'Maya Patel', age: 20, gender: 'Female',
    campus: 'UT Austin', major: 'Business', year: 'Sophomore',
    budget: { min: 700, max: 1000 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Early bird 🐦', cleanliness: 5, noise: 'Quiet', guests: 'Rarely',
    smoking: false, pets: true, bio: 'Business student and cat lover. I keep the place very clean and tend to sleep early. I\'d love a roommate who is respectful and studious.',
    interests: ['Yoga', 'Reading', 'Coffee', 'Travel', 'Photography'], initials: 'MP',
  },
  {
    id: 'r3', name: 'Chris Nguyen', age: 22, gender: 'Male',
    campus: 'Texas A&M', major: 'Engineering', year: 'Senior',
    budget: { min: 500, max: 800 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Flexible 😊', cleanliness: 3, noise: 'Moderate', guests: 'Sometimes',
    smoking: false, pets: false, bio: 'Aggie engineer. I spend most of my time in the lab or at the gym. Pretty easy-going about the apartment as long as common areas are decent.',
    interests: ['Football', 'Gym', 'Engineering', 'BBQ', 'Video games'], initials: 'CN',
  },
  {
    id: 'r6', name: 'Aisha Williams', age: 20, gender: 'Female',
    campus: 'Baylor', major: 'Pre-Med', year: 'Sophomore',
    budget: { min: 500, max: 750 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Flexible 😊', cleanliness: 5, noise: 'Quiet', guests: 'Rarely',
    smoking: false, pets: false, bio: 'Pre-med student who spends most of her time studying. Very clean and organized. Looking for a quiet, focused roommate who respects shared spaces.',
    interests: ['Medicine', 'Piano', 'Study groups', 'Church', 'Cooking'], initials: 'AW',
  },
];

const SPONSORS = [
  { id: 'sp1', name: 'CampusConnect Broadband', tagline: 'Fast student WiFi plans from $29/mo — no contracts!', emoji: '📡', gradient: 'linear-gradient(135deg,#0891b2,#17a2a2)', url: '#', cta: 'Get Connected' },
  { id: 'sp2', name: 'MoveEasy Student Movers', tagline: 'Local student moves starting at $99. TCU & campuses covered.', emoji: '🚛', gradient: 'linear-gradient(135deg,#7c3aed,#4f46e5)', url: '#', cta: 'Book a Move' },
  { id: 'sp3', name: 'SafeNest Renter Insurance', tagline: 'Protect your stuff — student renter insurance from $8/mo.', emoji: '🛡️', gradient: 'linear-gradient(135deg,#15803d,#16a34a)', url: '#', cta: 'Get a Quote' },
  { id: 'sp4', name: 'IKEA Student Discount', tagline: '10% off for students — furnish your new place for less!', emoji: '🛋️', gradient: 'linear-gradient(135deg,#f97316,#ea580c)', url: '#', cta: 'Shop Now' },
];
