const listings = [
  {
    id: 1,
    title: "Modern 2BR Near Campus",
    price: 850,
    priceUnit: "month",
    location: "0.3 miles from UT Austin",
    city: "Austin, TX",
    campus: "UT Austin",
    bedrooms: 2,
    bathrooms: 1,
    sqft: 875,
    type: "Apartment",
    available: "August 2025",
    description:
      "Bright, fully furnished 2-bedroom apartment just steps from UT campus. Updated kitchen, hardwood floors, in-unit washer/dryer. Perfect for two roommates. Landlord is responsive and professional.",
    amenities: [
      "In-unit W/D",
      "Dishwasher",
      "Hardwood floors",
      "Central A/C",
      "Pet friendly",
      "Parking included",
    ],
    landlord: "Alex Johnson",
    landlordEmail: "alex.johnson@realty.com",
    landlordPhone: "(512) 555-0182",
    featured: true,
    saved: false,
    icon: "🏢",
    rating: 4.8,
    reviews: 14,
  },
  {
    id: 2,
    title: "Cozy Studio — Walk to Baylor",
    price: 620,
    priceUnit: "month",
    location: "0.2 miles from Baylor",
    city: "Waco, TX",
    campus: "Baylor",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 480,
    type: "Studio",
    available: "July 2025",
    description:
      "Charming studio apartment within walking distance of Baylor University. Utilities included in rent. Quiet building, great for studying. Street parking available.",
    amenities: [
      "Utilities included",
      "Street parking",
      "Quiet building",
      "Laundry on-site",
      "Near bus route",
    ],
    landlord: "Maria Chen",
    landlordEmail: "mchen@housing.com",
    landlordPhone: "(254) 555-0237",
    featured: true,
    saved: false,
    icon: "🏠",
    rating: 4.5,
    reviews: 8,
  },
  {
    id: 3,
    title: "Spacious 4BR House — A&M",
    price: 600,
    priceUnit: "person/month",
    location: "0.5 miles from Texas A&M",
    city: "College Station, TX",
    campus: "Texas A&M",
    bedrooms: 4,
    bathrooms: 2,
    sqft: 1800,
    type: "House",
    available: "August 2025",
    description:
      "Large 4-bedroom house perfect for a group of friends. Big backyard, two full baths, garage with extra storage. Short drive or bike ride to Texas A&M. Split rent easily with roommates.",
    amenities: [
      "Backyard",
      "Garage",
      "2 full baths",
      "Central A/C & Heat",
      "Dishwasher",
      "2 parking spots",
    ],
    landlord: "Tom Williams",
    landlordEmail: "twilliams@tamu-rentals.com",
    landlordPhone: "(979) 555-0099",
    featured: true,
    saved: false,
    icon: "🏡",
    rating: 4.7,
    reviews: 22,
  },
  {
    id: 4,
    title: "Private Room in 3BR Apt — TCU",
    price: 700,
    priceUnit: "month",
    location: "0.4 miles from TCU",
    city: "Fort Worth, TX",
    campus: "TCU",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 200,
    type: "Room",
    available: "June 2025",
    description:
      "Private furnished bedroom in a 3-bedroom apartment shared with two other TCU students. Large common area, great roommates, quiet environment. Bills split equally.",
    amenities: [
      "Furnished bedroom",
      "Shared kitchen",
      "Netflix & WiFi",
      "Pool access",
      "Gym in building",
    ],
    landlord: "Sarah Park",
    landlordEmail: "sarah.park@tcuhousing.com",
    landlordPhone: "(817) 555-0340",
    featured: false,
    saved: false,
    icon: "🛏",
    rating: 4.6,
    reviews: 5,
  },
  {
    id: 5,
    title: "Luxury 1BR Condo — SMU",
    price: 1400,
    priceUnit: "month",
    location: "0.1 miles from SMU",
    city: "Dallas, TX",
    campus: "SMU",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 720,
    type: "Condo",
    available: "August 2025",
    description:
      "Upscale 1-bedroom condo in a modern building steps from SMU. Granite countertops, stainless appliances, balcony with city views. Concierge, rooftop pool, and fitness center included.",
    amenities: [
      "Rooftop pool",
      "Fitness center",
      "Concierge",
      "Balcony",
      "Covered parking",
      "Stainless appliances",
    ],
    landlord: "James Realty Group",
    landlordEmail: "leasing@jamesrealty.com",
    landlordPhone: "(214) 555-0078",
    featured: true,
    saved: false,
    icon: "🏙",
    rating: 4.9,
    reviews: 31,
  },
  {
    id: 6,
    title: "Affordable 2BR Duplex — UNT",
    price: 750,
    priceUnit: "month",
    location: "0.6 miles from UNT",
    city: "Denton, TX",
    campus: "UNT",
    bedrooms: 2,
    bathrooms: 1,
    sqft: 950,
    type: "Duplex",
    available: "September 2025",
    description:
      "Charming duplex with private entrance and fenced yard. Two spacious bedrooms, updated kitchen, and a covered porch. Quiet street, great for studying. Cats allowed.",
    amenities: [
      "Private entrance",
      "Fenced yard",
      "Covered porch",
      "Cats allowed",
      "Storage shed",
      "Street parking",
    ],
    landlord: "Linda Carter",
    landlordEmail: "linda@unt-rentals.net",
    landlordPhone: "(940) 555-0214",
    featured: false,
    saved: false,
    icon: "🏘",
    rating: 4.3,
    reviews: 9,
  },
  {
    id: 7,
    title: "3BR Townhome — Texas Tech",
    price: 800,
    priceUnit: "month",
    location: "0.8 miles from Texas Tech",
    city: "Lubbock, TX",
    campus: "Texas Tech",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1350,
    type: "Townhome",
    available: "August 2025",
    description:
      "Well-maintained 3-bedroom townhome with attached garage. Two-story layout, large master suite, community pool. Close to Tech campus and restaurants. Perfect for 3 roommates.",
    amenities: [
      "Attached garage",
      "Community pool",
      "Master suite",
      "2 full baths",
      "Dishwasher",
      "Washer/dryer connections",
    ],
    landlord: "West Texas Properties",
    landlordEmail: "info@wtproperties.com",
    landlordPhone: "(806) 555-0155",
    featured: false,
    saved: false,
    icon: "🏠",
    rating: 4.4,
    reviews: 17,
  },
  {
    id: 8,
    title: "Sublease — 1BR near UH",
    price: 900,
    priceUnit: "month",
    location: "0.3 miles from U of Houston",
    city: "Houston, TX",
    campus: "University of Houston",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    type: "Sublease",
    available: "May 2025",
    description:
      "Short-term sublease available May through August. Fully furnished 1BR apartment in a gated community. All utilities included. Great deal for summer semester students.",
    amenities: [
      "Fully furnished",
      "All utilities included",
      "Gated community",
      "Pool & gym",
      "Short-term lease OK",
    ],
    landlord: "Priya Nair",
    landlordEmail: "priya.sublease@gmail.com",
    landlordPhone: "(713) 555-0387",
    featured: true,
    saved: false,
    icon: "🔑",
    rating: 4.2,
    reviews: 3,
  },
  {
    id: 9,
    title: "Budget Studio — UT Austin",
    price: 550,
    priceUnit: "month",
    location: "1.1 miles from UT Austin",
    city: "Austin, TX",
    campus: "UT Austin",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 420,
    type: "Studio",
    available: "August 2025",
    description:
      "Affordable no-frills studio for students on a budget. Clean, safe building with laundry and bike storage. Bus stop right outside — easy commute to campus. Ideal for solo students.",
    amenities: [
      "Laundry on-site",
      "Bike storage",
      "Bus stop outside",
      "Water included",
      "Secure entry",
    ],
    landlord: "Austin Campus Housing",
    landlordEmail: "contact@austincampushousing.com",
    landlordPhone: "(512) 555-0044",
    featured: false,
    saved: false,
    icon: "🏠",
    rating: 4.0,
    reviews: 6,
  },
  {
    id: 10,
    title: "Roomy 2BR Apt with Pool — SMU",
    price: 1100,
    priceUnit: "month",
    location: "0.7 miles from SMU",
    city: "Dallas, TX",
    campus: "SMU",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    type: "Apartment",
    available: "August 2025",
    description:
      "Spacious 2-bed 2-bath apartment with resort-style pool and clubhouse. Each roommate gets a private bath. Walking distance to SMU and Greenville Ave restaurants. Valet trash.",
    amenities: [
      "Resort-style pool",
      "Clubhouse",
      "2 private baths",
      "Valet trash",
      "Package lockers",
      "Covered parking",
    ],
    landlord: "Uptown Living LLC",
    landlordEmail: "leasing@uptownliving.com",
    landlordPhone: "(214) 555-0201",
    featured: false,
    saved: false,
    icon: "🏊",
    rating: 4.7,
    reviews: 19,
  },
];

const campuses = [
  "All Campuses",
  "UT Austin",
  "Baylor",
  "Texas A&M",
  "TCU",
  "SMU",
  "UNT",
  "Texas Tech",
  "University of Houston",
];

const propertyTypes = [
  "All Types",
  "Apartment",
  "House",
  "Studio",
  "Room",
  "Condo",
  "Duplex",
  "Townhome",
  "Sublease",
];
