/* ============================================================
   LeaseLoop — Data (mock listings + roommate profiles)
   ============================================================ */

const CAMPUSES = [
  { id: 'ut-austin',   name: 'UT Austin',            emoji: '🤘', city: 'Austin, TX' },
  { id: 'baylor',      name: 'Baylor',               emoji: '🐻', city: 'Waco, TX' },
  { id: 'tamu',        name: 'Texas A&M',            emoji: '🐾', city: 'College Station, TX' },
  { id: 'tcu',         name: 'TCU',                  emoji: '🐸', city: 'Fort Worth, TX' },
  { id: 'smu',         name: 'SMU',                  emoji: '🏛',  city: 'Dallas, TX' },
  { id: 'unt',         name: 'UNT',                  emoji: '🦅', city: 'Denton, TX' },
  { id: 'ttu',         name: 'Texas Tech',           emoji: '🔴', city: 'Lubbock, TX' },
  { id: 'uh',          name: 'University of Houston',emoji: '🏙',  city: 'Houston, TX' },
];

const PROPERTY_TYPES = ['Apartment','House','Studio','Room','Condo','Duplex','Townhome','Sublease'];

const listings = [
  {
    id: 1, title: 'Modern 2BR Near Campus', price: 850, priceUnit: 'month',
    location: '0.3 miles from UT Austin', city: 'Austin, TX', campus: 'UT Austin',
    bedrooms: 2, bathrooms: 1, sqft: 875, type: 'Apartment', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Pets OK (deposit required)', parking: 'Included',
    utilities: ['Water', 'Trash'],
    description: 'Bright, fully furnished 2-bedroom apartment just steps from UT campus. Updated kitchen, hardwood floors, in-unit washer/dryer. Perfect for two roommates. Landlord is responsive and professional.',
    amenities: ['In-unit W/D','Dishwasher','Hardwood floors','Central A/C','Parking included','Furnished option'],
    landlord: 'Alex Johnson', landlordEmail: 'alex.johnson@realty.com', landlordPhone: '(512) 555-0182',
    landlordType: 'Realtor', agency: 'Capitol City Realty',
    featured: true, saved: false, icon: '🏢', rating: 4.8, reviews: 14, views: 342, inquiries: 8,
    status: 'available', postedBy: null,
  },
  {
    id: 2, title: 'Cozy Studio — Walk to Baylor', price: 620, priceUnit: 'month',
    location: '0.2 miles from Baylor', city: 'Waco, TX', campus: 'Baylor',
    bedrooms: 0, bathrooms: 1, sqft: 480, type: 'Studio', available: 'July 2025',
    leaseLength: '12 months', petPolicy: 'No pets', parking: 'Street parking',
    utilities: ['Water', 'Electricity', 'Internet'],
    description: 'Charming studio apartment within walking distance of Baylor University. All utilities included in rent. Quiet building, great for studying. Steps from campus shuttle.',
    amenities: ['All utilities included','Street parking','Quiet building','Laundry on-site','Near bus route'],
    landlord: 'Maria Chen', landlordEmail: 'mchen@housing.com', landlordPhone: '(254) 555-0237',
    landlordType: 'Private', agency: null,
    featured: true, saved: false, icon: '🏠', rating: 4.5, reviews: 8, views: 210, inquiries: 4,
    status: 'available', postedBy: null,
  },
  {
    id: 3, title: 'Spacious 4BR House — A&M', price: 600, priceUnit: 'person/month',
    location: '0.5 miles from Texas A&M', city: 'College Station, TX', campus: 'Texas A&M',
    bedrooms: 4, bathrooms: 2, sqft: 1800, type: 'House', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Dogs & Cats OK', parking: '2 spots included',
    utilities: ['Water', 'Trash'],
    description: 'Large 4-bedroom house perfect for a group of friends. Big backyard, two full baths, garage with extra storage. Short drive or bike ride to Texas A&M. Split rent easily with roommates.',
    amenities: ['Backyard','Garage','2 full baths','Central A/C & Heat','Dishwasher','2 parking spots'],
    landlord: 'Tom Williams', landlordEmail: 'twilliams@tamu-rentals.com', landlordPhone: '(979) 555-0099',
    landlordType: 'Private', agency: null,
    featured: true, saved: false, icon: '🏡', rating: 4.7, reviews: 22, views: 518, inquiries: 11,
    status: 'available', postedBy: null,
  },
  {
    id: 4, title: 'Private Room in 3BR Apt — TCU', price: 700, priceUnit: 'month',
    location: '0.4 miles from TCU', city: 'Fort Worth, TX', campus: 'TCU',
    bedrooms: 1, bathrooms: 1, sqft: 200, type: 'Room', available: 'June 2025',
    leaseLength: '9 months', petPolicy: 'No pets', parking: 'Building lot',
    utilities: ['All included'],
    description: 'Private furnished bedroom in a 3-bedroom apartment shared with two other TCU students. Large common area, great roommates, quiet environment. Bills split equally.',
    amenities: ['Furnished bedroom','Shared kitchen','Netflix & WiFi','Pool access','Gym in building'],
    landlord: 'Sarah Park', landlordEmail: 'sarah.park@tcuhousing.com', landlordPhone: '(817) 555-0340',
    landlordType: 'Private', agency: null,
    featured: false, saved: false, icon: '🛏', rating: 4.6, reviews: 5, views: 88, inquiries: 3,
    status: 'available', postedBy: null,
  },
  {
    id: 5, title: 'Luxury 1BR Condo — SMU', price: 1400, priceUnit: 'month',
    location: '0.1 miles from SMU', city: 'Dallas, TX', campus: 'SMU',
    bedrooms: 1, bathrooms: 1, sqft: 720, type: 'Condo', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Small pets OK', parking: 'Covered included',
    utilities: ['Water', 'Trash', 'Internet'],
    description: 'Upscale 1-bedroom condo steps from SMU. Granite countertops, stainless appliances, balcony with city views. Concierge, rooftop pool, and fitness center included.',
    amenities: ['Rooftop pool','Fitness center','Concierge','Balcony','Covered parking','Stainless appliances','Doorman'],
    landlord: 'James Realty Group', landlordEmail: 'leasing@jamesrealty.com', landlordPhone: '(214) 555-0078',
    landlordType: 'Realtor', agency: 'James Realty Group',
    featured: true, saved: false, icon: '🏙', rating: 4.9, reviews: 31, views: 872, inquiries: 19,
    status: 'available', postedBy: null,
  },
  {
    id: 6, title: 'Affordable 2BR Duplex — UNT', price: 750, priceUnit: 'month',
    location: '0.6 miles from UNT', city: 'Denton, TX', campus: 'UNT',
    bedrooms: 2, bathrooms: 1, sqft: 950, type: 'Duplex', available: 'September 2025',
    leaseLength: '12 months', petPolicy: 'Cats allowed', parking: 'Street parking',
    utilities: ['Water'],
    description: 'Charming duplex with private entrance and fenced yard. Two spacious bedrooms, updated kitchen, and a covered porch. Quiet street, great for studying.',
    amenities: ['Private entrance','Fenced yard','Covered porch','Cats allowed','Storage shed','Street parking'],
    landlord: 'Linda Carter', landlordEmail: 'linda@unt-rentals.net', landlordPhone: '(940) 555-0214',
    landlordType: 'Private', agency: null,
    featured: false, saved: false, icon: '🏘', rating: 4.3, reviews: 9, views: 154, inquiries: 2,
    status: 'available', postedBy: null,
  },
  {
    id: 7, title: '3BR Townhome — Texas Tech', price: 800, priceUnit: 'month',
    location: '0.8 miles from Texas Tech', city: 'Lubbock, TX', campus: 'Texas Tech',
    bedrooms: 3, bathrooms: 2, sqft: 1350, type: 'Townhome', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Dogs OK', parking: 'Attached garage',
    utilities: ['Water', 'Trash'],
    description: 'Well-maintained 3-bedroom townhome with attached garage. Two-story layout, large master suite, community pool. Close to Tech campus and restaurants.',
    amenities: ['Attached garage','Community pool','Master suite','2 full baths','Dishwasher','W/D connections'],
    landlord: 'West Texas Properties', landlordEmail: 'info@wtproperties.com', landlordPhone: '(806) 555-0155',
    landlordType: 'Realtor', agency: 'West Texas Properties',
    featured: false, saved: false, icon: '🏠', rating: 4.4, reviews: 17, views: 203, inquiries: 6,
    status: 'available', postedBy: null,
  },
  {
    id: 8, title: 'Sublease — 1BR near UH', price: 900, priceUnit: 'month',
    location: '0.3 miles from U of Houston', city: 'Houston, TX', campus: 'University of Houston',
    bedrooms: 1, bathrooms: 1, sqft: 650, type: 'Sublease', available: 'May 2025',
    leaseLength: 'May–August (short-term)', petPolicy: 'No pets', parking: 'Gated lot',
    utilities: ['All included'],
    description: 'Short-term sublease available May through August. Fully furnished 1BR in a gated community. All utilities included. Great for summer semester students.',
    amenities: ['Fully furnished','All utilities included','Gated community','Pool & gym','Short-term OK'],
    landlord: 'Priya Nair', landlordEmail: 'priya.sublease@gmail.com', landlordPhone: '(713) 555-0387',
    landlordType: 'Private', agency: null,
    featured: true, saved: false, icon: '🔑', rating: 4.2, reviews: 3, views: 96, inquiries: 2,
    status: 'available', postedBy: null,
  },
  {
    id: 9, title: 'Budget Studio — UT Austin', price: 550, priceUnit: 'month',
    location: '1.1 miles from UT Austin', city: 'Austin, TX', campus: 'UT Austin',
    bedrooms: 0, bathrooms: 1, sqft: 420, type: 'Studio', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'No pets', parking: 'Street parking',
    utilities: ['Water'],
    description: 'Affordable studio for students on a budget. Clean, safe building with laundry and bike storage. Bus stop outside — easy commute to campus.',
    amenities: ['Laundry on-site','Bike storage','Bus stop outside','Water included','Secure entry'],
    landlord: 'Austin Campus Housing', landlordEmail: 'contact@austincampushousing.com', landlordPhone: '(512) 555-0044',
    landlordType: 'Realtor', agency: 'Austin Campus Housing',
    featured: false, saved: false, icon: '🏠', rating: 4.0, reviews: 6, views: 178, inquiries: 3,
    status: 'available', postedBy: null,
  },
  {
    id: 10, title: 'Roomy 2BR Apt with Pool — SMU', price: 1100, priceUnit: 'month',
    location: '0.7 miles from SMU', city: 'Dallas, TX', campus: 'SMU',
    bedrooms: 2, bathrooms: 2, sqft: 1050, type: 'Apartment', available: 'August 2025',
    leaseLength: '12 months', petPolicy: 'Small pets OK', parking: 'Covered included',
    utilities: ['Water', 'Trash', 'Internet'],
    description: 'Spacious 2-bed 2-bath with resort-style pool and clubhouse. Each roommate gets a private bath. Walking distance to SMU and Greenville Ave restaurants.',
    amenities: ['Resort-style pool','Clubhouse','2 private baths','Valet trash','Package lockers','Covered parking'],
    landlord: 'Uptown Living LLC', landlordEmail: 'leasing@uptownliving.com', landlordPhone: '(214) 555-0201',
    landlordType: 'Realtor', agency: 'Uptown Living LLC',
    featured: false, saved: false, icon: '🏊', rating: 4.7, reviews: 19, views: 432, inquiries: 9,
    status: 'available', postedBy: null,
  },
];

/* ── Sample Roommate Profiles ─────────────────────────────── */
const roommateProfiles = [
  {
    id: 'r1', name: 'Jordan Lee', age: 21, gender: 'Non-binary',
    campus: 'UT Austin', major: 'Computer Science', year: 'Junior',
    budget: { min: 600, max: 900 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Night owl 🦉', cleanliness: 4, noise: 'Moderate', guests: 'Sometimes',
    smoking: false, pets: false, bio: 'CS major who loves hackathons, hiking around Austin, and cooking for friends. Looking for a chill roommate who won\'t mind me occasionally coding late.',
    interests: ['Coding', 'Hiking', 'Cooking', 'Gaming', 'Music'], initials: 'JL',
  },
  {
    id: 'r2', name: 'Maya Patel', age: 20, gender: 'Female',
    campus: 'UT Austin', major: 'Business', year: 'Sophomore',
    budget: { min: 700, max: 1000 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Early bird 🐦', cleanliness: 5, noise: 'Quiet', guests: 'Rarely',
    smoking: false, pets: true, bio: 'Business student and cat lover. I keep the place very clean and tend to sleep early. I\'d love a roommate who is respectful and studious.',
    interests: ['Yoga', 'Reading', 'Coffee', 'Travel', 'Photography'], initials: 'MP',
  },
  {
    id: 'r3', name: 'Chris Nguyen', age: 22, gender: 'Male',
    campus: 'Texas A&M', major: 'Engineering', year: 'Senior',
    budget: { min: 500, max: 800 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Flexible 😊', cleanliness: 3, noise: 'Moderate', guests: 'Sometimes',
    smoking: false, pets: false, bio: 'Aggie engineer. I spend most of my time in the lab or at the gym. Pretty easy-going about the apartment as long as common areas are decent.',
    interests: ['Football', 'Gym', 'Engineering', 'BBQ', 'Video games'], initials: 'CN',
  },
  {
    id: 'r4', name: 'Sofia Ramirez', age: 21, gender: 'Female',
    campus: 'SMU', major: 'Communications', year: 'Junior',
    budget: { min: 900, max: 1400 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Night owl 🦉', cleanliness: 4, noise: 'Lively', guests: 'Often',
    smoking: false, pets: false, bio: 'Comm major and aspiring journalist. Dallas social scene is my thing. Looking for someone outgoing who doesn\'t mind occasional friends over on weekends.',
    interests: ['Fashion', 'Social media', 'Brunch', 'Tennis', 'Art museums'], initials: 'SR',
  },
  {
    id: 'r5', name: 'Tyler Brooks', age: 23, gender: 'Male',
    campus: 'TCU', major: 'Education', year: 'Senior',
    budget: { min: 600, max: 900 }, moveIn: 'July 2025', leaseDuration: '9 months',
    sleepSchedule: 'Early bird 🐦', cleanliness: 4, noise: 'Quiet', guests: 'Rarely',
    smoking: false, pets: true, bio: 'Future teacher and dog dad. My golden retriever Biscuit is the best roommate you\'ll ever meet. I\'m tidy, keep to myself, and love a clean space.',
    interests: ['Dogs', 'Running', 'Teaching', 'Basketball', 'Podcasts'], initials: 'TB',
  },
  {
    id: 'r6', name: 'Aisha Williams', age: 20, gender: 'Female',
    campus: 'Baylor', major: 'Pre-Med', year: 'Sophomore',
    budget: { min: 500, max: 750 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Flexible 😊', cleanliness: 5, noise: 'Quiet', guests: 'Rarely',
    smoking: false, pets: false, bio: 'Pre-med student who spends most of her time studying. Very clean and organized. Looking for a quiet, focused roommate who respects shared spaces.',
    interests: ['Medicine', 'Piano', 'Study groups', 'Church', 'Cooking'], initials: 'AW',
  },
  {
    id: 'r7', name: 'Derek Kim', age: 22, gender: 'Male',
    campus: 'UNT', major: 'Music', year: 'Junior',
    budget: { min: 500, max: 800 }, moveIn: 'September 2025', leaseDuration: '12 months',
    sleepSchedule: 'Night owl 🦉', cleanliness: 3, noise: 'Moderate', guests: 'Sometimes',
    smoking: false, pets: false, bio: 'Music major and part-time DJ. I practice with headphones, I promise! Looking for someone who appreciates good music and doesn\'t stress over dishes.',
    interests: ['Music', 'DJing', 'Concerts', 'Coffee shops', 'Skateboarding'], initials: 'DK',
  },
  {
    id: 'r8', name: 'Priya Sharma', age: 21, gender: 'Female',
    campus: 'University of Houston', major: 'Finance', year: 'Junior',
    budget: { min: 700, max: 1000 }, moveIn: 'August 2025', leaseDuration: '12 months',
    sleepSchedule: 'Early bird 🐦', cleanliness: 5, noise: 'Quiet', guests: 'Sometimes',
    smoking: false, pets: false, bio: 'Finance major interning downtown this summer. I\'m organized, clean, and love to cook Indian food. Would love a roommate who enjoys home-cooked meals!',
    interests: ['Finance', 'Cooking', 'Bollywood', 'Hiking', 'Reading'], initials: 'PS',
  },
];
