cat > utils/data.js << 'EOF'
const SAMPLE_LISTINGS = [
  {
    id: 1,
    title: 'Modern 2BR near Campus',
    type: 'sublease',
    campus: 'ut-austin',
    price: 1200,
    bedrooms: 2,
    bathrooms: 1,
    description: 'Newly renovated apartment, furnished, utilities included',
    image: '🏠',
    distance: 0.5,
    postedBy: 'John D.',
    date: '2 days ago',
  },
  {
    id: 2,
    title: 'Seeking Roommate - 3BR House',
    type: 'roommate',
    campus: 'ut-austin',
    price: 600,
    bedrooms: 1,
    bathrooms: 1,
    description: 'Looking for a clean, quiet roommate. Great neighborhood',
    image: '����',
    distance: 1.2,
    postedBy: 'Sarah M.',
    date: '1 week ago',
  },
  {
    id: 3,
    title: 'Recently Renovated Home',
    type: 'home-sale',
    campus: 'tcu',
    price: 450000,
    bedrooms: 3,
    bathrooms: 2,
    description: 'Perfect for faculty and families. Walking distance to campus',
    image: '🏡',
    distance: 0.8,
    postedBy: 'Real Estate Co.',
    date: '3 days ago',
  },
  {
    id: 4,
    title: 'New Build Apartments - Pre-Lease',
    type: 'new-build',
    campus: 'smu',
    price: 1500,
    bedrooms: 2,
    bathrooms: 2,
    description: 'State-of-the-art amenities, gym, pool, rooftop lounge',
    image: '🏗',
    distance: 0.3,
    postedBy: 'Developer',
    date: 'Today',
  },
];
EOF